version: "3"

services:
  agent:
    user: root
    privileged: true
    image: agent:latest
    ports:
      - "6008:6008"
    restart: always
    volumes:
      - ./agent/:/agent/
      - ./ec7223a39ce59f226a68acc30dc1af2788490e15:/tmp/data-gym-cache/ec7223a39ce59f226a68acc30dc1af2788490e15
    command: ["/bin/bash", "-c", "cd agent && python -m server"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
